Villager0:
  #FORMAT: bargain 1, amount 1, *bargain 2 (optional), *amount 2 (optional), product, amount of product
  #bargain = item you give in exchange for product
  #last item is always the product
  Trades:
    Trade0: EMERALD, 30, SPAWNER, 1
    Trade1: EMERALD, 15, PIG_SPAWN_EGG, 1
    Trade2: EMERALD, 20, SKELETON_SPAWN_EGG, 1
    Trade3: EMERALD, 20, SPIDER_SPAWN_EGG, 1
    Trade4: EMERALD, 20, CREEPER_SPAWN_EGG, 1
Villager1:
  #FORMAT: bargain 1, amount 1, *bargain 2 (optional), *amount 2 (optional), product, amount of product
  #bargain = item you give in exchange for product
  #last item is always the product
  Trades:
    Trade0: EMERALD, 25, BARREL, 1
    Trade1: EMERALD, 5, PISTON, 1
    Trade2: EMERALD, 2, SLIME_BALL, 1
    Trade3: EMERALD, 1, REDSTONE, 4
    Trade4: EMERALD, 5, DISPENSER, 1
