name: SkyblockGambit
version: '1.0-SNAPSHOT'
main: org.jacobn99.skyblockgambit.SkyblockGambit
api-version: '1.20'


commands:
  start:
  debug:
  t:
  set_spawn:
  spawn_villager:
  add_custom_item:
  set_custom_item:
  get_custom_item:
  set_starter_chest:
  end:
  list_custom_items:
  clear_custom_items:
  grant_advancement:
  clear_world:
  tasks:
  kill_skulls:
  generate_new_map:
  reset_villagers: